<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Portal2BetaLauncher</AssemblyName>
    <RootNamespace>Portal2BetaLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../EmbeddedFixes.zip" Link="EmbeddedFixes.zip" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
